apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: messaging
        image: 482053628475.dkr.ecr.eu-central-1.amazonaws.com/usupport-messaging-api:beta
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: messaging-secrets
        - configMapRef:
            name: messaging-config
        ports:
        - containerPort: 3006
      imagePullSecrets:
      - name: regcred
